

services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning  
    
  backend:
    build: .
    env_file:
      - .env  
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - smtp4dev
      - redis
    environment:
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False
  worker:
    build: .
    command: celery -A core worker --loglevel=info  
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
  beat:
    build: .
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
      - worker
  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "3000:80"      # Web UI
      - "25:25"        # SMTP Server
    volumes:
      - smtp4dev-data:/app/data   # ذخیره ایمیل‌ها

volumes:
  smtp4dev-data:

